#!/bin/sh
# Startx
# dwm

# ensure that xinit scripts are sourced
# this should help with slow application startup
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xrandr --output HDMI-0 --same-as DVI-D-0	# Set TV (hdmi) to be the same as main monitor
redshift-gtk &					# Redshift for bluelight filter
volumeicon &
dwmblocks &					# Start dwmblocks
dunst &						# Dunst for notifications
picom &						# Picom for transparency
mpd &						# music player daemon
#mpDris2 &					# control mpd with playerctl
setxkbmap -option caps:escape			# Set caps lock to escape
#imwheel -b 45 &					# Faster scroll speed
clipmenud &					# Clipmenu
nitrogen --restore				# Restore wallpaper
conky -c ~/.config/conky/conkyrc.dwm &		# Start conky
xset s 900					# Blankout screen after 15 minutes
lxsession &					# Start policy kit
#exec dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY &		# temp fix for slow application startup
exec dwm					# Start dwm
