#!/usr/bin/env bash

## General ##
#alias ls="ls --color=auto --group-directories-first"
#alias la="ls -lA --color=auto --group-directories-first"
alias ls="lsd --group-directories-first"
alias la="lsd --almost-all --long --total-size --group-directories-first"
alias lss="/usr/bin/ls -1 --color=auto --group-directories-first"
alias grep="grep --color=auto"
alias f="ranger"
alias sf="sudo ranger"
alias x="exit"
alias vim="nvim"
alias sdn="shutdown now"
alias trem="transmission-remote"
alias py="python"
alias ka="killall"

## yt-dlp ##
alias ytv="yt-dlp --config-location ~/.config/youtube-dl/video"
alias yta="yt-dlp --config-location ~/.config/youtube-dl/audio"
alias ytap="yt-dlp --config-location ~/.config/youtube-dl/audio_playlist"
alias ytas="yt-dlp --config-location ~/.config/youtube-dl/audio_split"
alias ytvp="yt-dlp --config-location ~/.config/youtube-dl/video_playlist"
alias ytpod="yt-dlp --config-location ~/.config/youtube-dl/podcast"

## Vimwiki ##
alias wiki="nvim -c VimwikiIndex"

## Games ##

## Directories ##
alias gc="cd /mnt/x/game-stuff/game-collection"
