#!/usr/bin/env bash

alias ka="killall"
#alias ls="ls --color=auto --group-directories-first"
#alias la="ls -lA --color=auto --group-directories-first"
alias ls="lsd -1 --group-directories-first"
alias la="lsd -lA --group-directories-first"
alias grep="grep --color=auto"
alias f="ranger"
alias sf="sudo ranger"
alias e="explorer.exe ."
alias x="exit"
alias t="tmux -f ~/.config/tmux/tmux.conf"
alias c="calcurse"
alias vim="nvim"

# yt-dlp
alias ytv="yt-dlp --config-location ~/.config/youtube-dl/video"
alias yta="yt-dlp --config-location ~/.config/youtube-dl/audio"
alias ytap="yt-dlp --config-location ~/.config/youtube-dl/audio_playlist"
alias ytas="yt-dlp --config-location ~/.config/youtube-dl/audio_split"
alias ytvp="yt-dlp --config-location ~/.config/youtube-dl/video_playlist"
alias ytpod="yt-dlp --config-location ~/.config/youtube-dl/podcast"

# Vimwiki
alias wiki="nvim -c VimwikiIndex"

# git
alias g="git"
alias ga="git add"
alias gc="git commit"
alias gac="git commit -a"
alias gf="git fetch"
alias gp="git pull"

# yadm
alias y="yadm"
alias ys="yadm status"
alias yc="yadm commit"
alias ya="yadm add"
alias yp="yadm push"

alias sdn="shutdown now"
alias n="notes"
alias bat="cmd.exe /c"
alias trem="transmission-remote"
alias py="python"
alias xrr="xmonad --recompile && xmonad --restart && arcolinux-restart-polybar && notify-send 'xmonad rebuild'"

# dotfiles
alias config="/usr/bin/git --git-dir=$HOME/dotfiles --work-tree=$HOME"
alias clist="/usr/bin/git --git-dir=$HOME/dotfiles --work-tree=$HOME ls-tree --full-tree -r --name-only HEAD"

# Games
alias factorio="lutris lutris:rungameid/2"
alias eldenring="gamemoderun mangohud ~/Games/Elden.Ring-jc141/start.w.sh"
alias gtavc="lutris lutris:rungameid/16"
alias gtav="lutris lutris:rungameid/10"
alias hl2="lutris lutris:rungameid/18"
alias saints="lutris lutris:rungameid/7"
alias silent-hill="lutris lutris:rungameid/14"
alias terraria="lutris lutris:rungameid/1"
alias witcher="lutris lutris:rungameid/12"
alias xonotic="lutris lutris:rungameid/13"
