#!/usr/bin/env bash

alias ka="killall"
#alias ls="ls --color=auto --group-directories-first"
#alias la="ls -lA --color=auto --group-directories-first"
alias ls="lsd -1 --group-directories-first"
alias la="lsd -lA --group-directories-first"
alias grep="grep --color=auto"
alias f="ranger"
alias sf="sudo ranger"
alias e="explorer.exe ."
alias x="exit"
alias t="tmux -f ~/.config/tmux/tmux.conf"
alias c="calcurse"
alias vim="nvim"

# yt-dlp
alias ytv="yt-dlp"
alias yta="yt-dlp --config-location ~/.config/youtube-dl/audio"
alias ytap="yt-dlp --config-location ~/.config/youtube-dl/playlist_audio"
alias ytvp="yt-dlp --config-location ~/.config/youtube-dl/playlist_video"
alias ytpod="yt-dlp --config-location ~/.config/youtube-dl/podcast"

alias wiki="nvim -c VimwikiIndex"

# git
alias g="git"
alias ga="git add"
alias gc="git commit"
alias gac="git commit -a"
alias gf="git fetch"
alias gp="git pull"

# yadm
alias y="yadm"
alias ys="yadm status"
alias yc="yadm commit"
alias ya="yadm add"
alias yp="yadm push"
alias updatecal="yadm add -A $HOME/.local/share/calcurse && yadm commit -m \"Calcurse Update\""

alias sdn="shutdown now"
alias n="notes"
alias bat="cmd.exe /c"
alias trem="transmission-remote"
alias py="python"
alias xrr="xmonad --recompile && xmonad --restart && arcolinux-restart-polybar && notify-send 'xmonad rebuild'"
alias config="/usr/bin/git --git-dir=$HOME/dotfiles --work-tree=$HOME"
alias clist="/usr/bin/git --git-dir=$HOME/dotfiles --work-tree=$HOME ls-tree --full-tree -r --name-only HEAD"
